apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: istio-public-gateway-waf-wasm
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-public-gateway
  url: oci://ghcr.io/corazawaf/coraza-proxy-wasm:main
  imagePullPolicy: Always
  pluginConfig:
    rules:
      - "SecDebugLogLevel 3"
      - "SecRuleEngine On"
      - "SecRule REQUEST_URI \"@streq /admin\" \"id:102,phase:1,t:lowercase,deny\""
