apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-public-gateway-waf-1.16
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-public-gateway
      istio: ingressgateway
  configPatches:
    - applyTo: EXTENSION_CONFIG
      match:
        proxy:
          proxyVersion: ^1\.16.*
      patch:
        operation: ADD
        value:
          name: istio-public-gateway-waf
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
            config:
              root_id: istio-public-gateway-waf-root-id
              vm_config:
                vm_id: istio-public-gateway-waf-vm-id
                runtime: envoy.wasm.runtime.v8
                code:
                  remote:
                    http_uri:
                      uri: https://github.com/zufardhiyaulhaq/coraza-proxy-wasm/raw/extension-v1/main.wasm
                      timeout: "60s"
              configuration:
                "@type": "type.googleapis.com/google.protobuf.StringValue"
                value: |
                  {
                    "rulesets": [{
                        "rules": [
                          "Include @demo-conf",
                          "Include @crs-setup-demo-conf",
                          "SecDefaultAction \"phase:3,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:4,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:5,log,auditlog,pass\"",
                          "SecDebugLogLevel 3",
                          "Include @owasp_crs/*.conf"
                        ],
                        "authority": "podinfo.zufardhiyaulhaq.com"
                      },
                      {
                        "rules": [
                          "Include @demo-conf",
                          "Include @crs-setup-demo-conf",
                          "SecDefaultAction \"phase:3,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:4,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:5,log,auditlog,pass\"",
                          "SecDebugLogLevel 3",
                          "Include @owasp_crs/*.conf"
                        ],
                        "authority": "argocd.zufardhiyaulhaq.com"
                      },
                      {
                        "rules": [
                          "Include @demo-conf",
                          "Include @crs-setup-demo-conf",
                          "SecDefaultAction \"phase:3,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:4,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:5,log,auditlog,pass\"",
                          "SecDebugLogLevel 3",
                          "Include @owasp_crs/*.conf"
                        ],
                        "authority": "sakura.zufardhiyaulhaq.com"
                      },
                      {
                        "rules": [
                          "Include @demo-conf",
                          "Include @crs-setup-demo-conf",
                          "SecDefaultAction \"phase:3,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:4,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:5,log,auditlog,pass\"",
                          "SecDebugLogLevel 3",
                          "Include @owasp_crs/*.conf"
                        ],
                        "authority": "grafana.zufardhiyaulhaq.com"
                      },
                      {
                        "rules": [
                          "Include @demo-conf",
                          "Include @crs-setup-demo-conf",
                          "SecDefaultAction \"phase:3,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:4,log,auditlog,pass\"",
                          "SecDefaultAction \"phase:5,log,auditlog,pass\"",
                          "SecDebugLogLevel 3",
                          "Include @owasp_crs/*.conf"
                        ],
                        "authority": "bookinfo.zufardhiyaulhaq.com"
                      }
                    ],
                    "identifier": "istio-public-gateway"
                  }
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.rbac
        proxy:
          proxyVersion: ^1\.16.*
      patch:
        operation: INSERT_AFTER
        value:
          name: istio-public-gateway-waf
          config_discovery:
            config_source:
              ads: {}
            type_urls:
              ["type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"]
