apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: podinfo-zufardhiyaulhaq-com-modsecurity-1.16
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-public-gateway
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            sni: podinfo.zufardhiyaulhaq.com
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
        proxy:
          proxyVersion: ^1\.16.*
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
            config:
              name: podinfo.zufardhiyaulhaq.com-modsecurity
              root_id: podinfo.zufardhiyaulhaq.com-modsecurity
              vm_config:
                vm_id: podinfo.zufardhiyaulhaq.com-modsecurity
                code:
                  remote:
                    sha256: "88689b8d4386dd686beb303a7d7d5e59978f21e15d04d68a59289728117a54d9"
                    http_uri:
                      uri: https://github.com/zufardhiyaulhaq/community-ops/raw/master/resources/modsecurity-filter.wasm
                      timeout: "10s"
                      cluster: "PassthroughCluster"
                configuration:
                  "@type": "type.googleapis.com/google.protobuf.StringValue"
                  value: |
                      {"rules":"SecRuleEngine On"}
