resources:
# Namespace
- namespaces/default
- namespaces/falco-system
- namespaces/infrastructure
- namespaces/istio-system
- namespaces/argocd-system
- namespaces/observability-system
- namespaces/kubecost-system
- namespaces/community
